### ISSUE TITLE
Build Fails on Window

### ISSUE THREAD

**Issue by adnanmunawar** [mkazhdan/EDT#3]
System Information:
Windows 10
MSVC Version: Microsoft Visual Studio Community 2019 Version 16.9.0

Multiple errors relating to including files such as:

```
Error (active)	E1696 cannot open source file "Misha/Geometry.h" EDTFromMesh C:\Users\Adnan Munawar\Desktop\EDT\EDTFromMesh\EDTFromMesh.cpp	32	

```

**Comment by mkazhdan** [comment]
Are you using the Release/x64 build?

**Comment by adnanmunawar** [comment]
Hi Misha, Thank you for the prompt response. I was using Debug/x64 when I opened this issue. Changing it to Release/x64 allows for successful compilation.
